project:
  type: website

website:
  title: "My journey"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Arya20040110
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: sandstone
    css: styles.css



